app/mod_profile/controllers.py
import random
import os
import json
import re
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for

from sqlalchemy import desc

# Import login manager
from flask.ext.login import LoginManager, UserMixin, login_required, login_user, current_user

# Import the database object from the main app module
from app import db
from app import app

# Import module forms
#from app.mod_card.forms import CreateCardForm

# Import module models (i.e. User)
from app.mod_card.models import Card, UserCards
from app.mod_auth.models import User
from app.mod_trade.models import TradeHeader

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_profile = Blueprint('profiles', __name__, url_prefix='/profiles')

@mod_profile.route('/')
def index():
	users = User.query.all()
	return render_template( "profile/index.html", users = users)

@mod_profile.route('/<name>')
@login_required
def view(name):
	user = User.query.filter(User.name.like(name)).first()
	#if user.id == current_user.id:
	#	trades = TradeHeader.query.filter((TradeHeader.user1_id == current_user.id) | (TradeHeader.user2_id == current_user.id))
	#	return "This is you"
	return redirect(url_for('profiles.cardIndex',name=name))

@mod_profile.route('/<name>/cards')
@login_required
def cardIndex(name):
	user = User.query.filter(User.name.like(name)).first()
	if not user:
		return "No such user", 404
	cardLookup = user.cards.order_by(desc(UserCards.date_modified)).group_by(UserCards.card_id, UserCards.holo)
	cards = []
	holoList = []
	quantities = []
	for i in cardLookup:
		card = Card.query.filter_by(id=i.card_id).first()
		count = user.cards.filter(UserCards.card_id == card.id, UserCards.holo == i.holo).count()
		quantities.append(count)
		cards.append(card)
		holoList.append(i.holo)
	return render_template(	"profile/view.html",
				user = user,
				cards = cards,
				cardLookup = cardLookup,
				holoList=holoList,
				quantities=quantities,
				textBackground = app.config['TEXT_BACKGROUND'],
                                borderColor=app.config['BORDER_COLOR'],
                                cardsPerRow=app.config['CARDS_PER_ROW'])

@mod_profile.route('/<name>/card/<id>')
@login_required
def cardKind(name,id):
	user = User.query.filter(User.name.like(name)).first()
	if not user:
		return "No such user", 404
	holo = request.args.get('holo') == "True"
	cards = user.cards.filter(UserCards.card_id == id, UserCards.holo == holo).order_by(desc(UserCards.id)).all()
	if not cards:
		return "That user doesn't have any of that card", 404
	card = Card.query.filter_by(id=cards[0].card_id).first()
	cardLookup = card
	return render_template( "profile/kind.html",
                                user = user,
				cards = cards,
                                card = card,
                                cardLookup = card,
                                holo = holo,
                                textBackground = app.config['TEXT_BACKGROUND'],
                                borderColor = app.config['BORDER_COLOR'])		

@mod_profile.route('/<name>/cards/<id>')
@login_required
def viewUserCard(name,id):
        user = User.query.filter(User.name.like(name)).first()
        if not user:
                return "no such user", 400
        card = user.cards.filter_by(id=id).first()
        if not card:
                return "no such card for that user", 400
	
        cardType = Card.query.filter_by(id=card.card_id).first()
        holo = card.holo
        if current_user.id == user.id:
                ownedCard = True
        else:
                ownedCard = False
	cardHistory = []
	id = re.escape(id)
	result = db.engine.execute('SELECT * FROM trade_line JOIN trade_header ON trade_header.id = trade_line.trade_id AND trade_line.card_id = '+id+' JOIN	user u1 ON u1.id = trade_header.user1_id JOIN user u2 ON u2.id = trade_header.user2_id ORDER BY trade_line.id desc;')
	for row in result:
		offering = row[5]
		givingName = ''
		gettingName = ''
		user1 = row[9]
		user2 = row[10]
		if offering == user1:
			givingName = row[19]
			gettingName = row[24]
		else:
			givingName = row[24]
			gettingName = row[19]
		cardHistory.append({'giving':givingName,'getting':gettingName,'date': row[1][0:10]})
	origin = {}
	origin['puller'] = user.name
	origin['date'] = str(card.date_created)[0:10]
	if len(cardHistory):
		origin['puller'] = cardHistory[len(cardHistory)-1]['giving']
        return render_template( "profile/card.html",
                                user = user,
                                card = cardType,
                                cardLookup = card,
                                holo = holo,
                                ownedCard = ownedCard,
				cardHistory = cardHistory,
				origin = origin,
				justPulled = False,
                                textBackground = app.config['TEXT_BACKGROUND'],
                                borderColor = app.config['BORDER_COLOR'])

@mod_profile.route('/<name>/cards/<cardId>/delete', methods=['POST'])
@login_required
def deleteCard(name,cardId):
	user = User.query.filter(User.name.like(name)).first()
	if user.id is not current_user.id:
		return "please don't try that again", 400
        if not user:
                return "no such user", 400
	card = user.cards.filter_by(id=cardId).first()
        if not card:
                return "no such card for that user", 400
	db.session.delete(card)
	db.session.commit()
	return redirect(url_for('profiles.view', name=user.name))

app/mod_trade/controllers.py
import random
import os
import json
import datetime
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for

from sqlalchemy import desc, or_

# Import login manager
from flask.ext.login import LoginManager, UserMixin, login_required, login_user, current_user

# Import the database object from the main app module
from app import db
from app import app

# Import module forms
#from app.mod_card.forms import CreateCardForm

# Import module models (i.e. User)
from app.mod_card.models import Card, UserCards
from app.mod_auth.models import User
from app.mod_trade.models import TradeHeader, TradeLine

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_trade = Blueprint('trade', __name__, url_prefix='/trades')

def returnFullTrade(trade_id):
	toReturn = {}
	toReturn['lines'] = []
	line = {}
	trade = TradeHeader.query.filter_by(id=trade_id).first()
	for key, value in trade.__dict__.items():
		if type(value) is str or type(value) is int or type(value) is bool or type(value) is unicode or type(value) is datetime.datetime:
			toReturn[key] = value
		else:
			print(key + " " + str(type(value)))

	user = User.query.filter_by(id=trade.user1_id).first()
	toReturn['user1_name'] = user.name

	user = User.query.filter_by(id=trade.user2_id).first()
        toReturn['user2_name'] = user.name

	for trade_line in trade.lines:
		line = {}
		line['card'] = {}
		for key, value in trade_line.__dict__.items():
			if type(value) is str or type(value) is int or type(value) is bool or type(value) is unicode:
				line[key] = value
		user_card = UserCards.query.filter_by(id=trade_line.card_id).first()
		if not user_card:
			continue
		card = Card.query.filter_by(id=user_card.card_id).first()
		for key, value in card.__dict__.items():
			if type(value) is str or type(value) is int or type(value) is bool or type(value) is unicode:
				line['card'][key] = value
		line['holo'] = user_card.holo
		toReturn['lines'].append(line)

	if toReturn['user1_id'] == current_user.id:
		user = User.query.filter_by(id=toReturn['user2_id']).first()
		toReturn['otherUser_name'] = user.name
	else:
		user = User.query.filter_by(id=toReturn['user1_id']).first()
		toReturn['otherUser_name'] = user.name
			
	return toReturn

@mod_trade.route('/<id>/addCards', methods=['POST'])
@login_required
def addCards(id):
	trade = TradeHeader.query.filter_by(id=id).first()
	user = User.query.filter_by(id=current_user.id).first()
        if not trade:
                return "No such trade", 400
        if current_user.id != trade.user1_id and current_user.id != trade.user2_id:
                return "You are not involved in this trade", 400
	if not trade.active:
                return "This trade is complete", 400
	data = json.loads(request.form['checkedIds'])
	for card in data:
		if int(card['quantity']) < 1:
			continue
		tradeLine = TradeLine(trade_id = trade.id, card_id = card['id'], offering_user = current_user.id)
        	db.session.add(tradeLine)
        	db.session.commit()
		if int(card['quantity']) > 1:
			cardKind = user.cards.filter(UserCards.id == card['id']).first()
			usedIds = []
			for line in trade.lines.all():
				usedIds.append(line.card_id)
			for i in range(1,int(card['quantity'])):
				toRemove = user.cards.filter(UserCards.card_id == cardKind.card_id,~UserCards.id.in_(usedIds)).first()
				if not toRemove:
					continue
				tradeLine = TradeLine(trade_id = id, card_id = toRemove.id, offering_user = current_user.id)
				db.session.add(tradeLine)
				db.session.commit()
				usedIds.append(toRemove.id)
	trade.user2_approved = False
	trade.user1_approved = False
	db.session.commit()

	return "lines added", 200

@mod_trade.route('/<id>/removeCard', methods=['POST'])
@login_required
def removeCard(id):
	trade = TradeHeader.query.filter_by(id=id).first()
        if not trade:
                return "No such trade", 400
        if current_user.id != trade.user1_id and current_user.id != trade.user2_id:
                return "You are not involved in this trade", 400
	if not trade.active:
		return "This trade is complete", 400
	tradeLine = trade.lines.filter_by(card_id=int(request.form['cardId'])).first()
	db.session.delete(tradeLine)
        trade.user2_approved = False
        trade.user1_approved = False
        db.session.commit()
	return "line removed", 200

@mod_trade.route('/<id>/approve', methods=['POST'])
@login_required
def approve(id):
	trade = TradeHeader.query.filter_by(id=id).first()
	if not trade:
                return "No such trade", 400
        if current_user.id != trade.user1_id and current_user.id != trade.user2_id:
                return "You are not involved in this trade", 400
	if not trade.active:
                return "This trade is complete", 400

	if current_user.id == trade.user1_id:
		trade.user1_approved = True;
	else:
		trade.user2_approved = True;
	db.session.commit()
	if trade.user1_approved and trade.user2_approved:
		trade.active = False
		processTrade(id)
	return redirect(url_for('trade.showTrade', id=id))

def processTrade(id):
	trade = TradeHeader.query.filter_by(id=id).first()
	building = []
	for line in trade.lines.all():
		user = User.query.filter_by(id = line.offering_user).first()
		card = user.cards.filter_by(id = line.card_id).first()
		if not card:
			continue
		if line.offering_user == trade.user1_id:
			card.user_id = trade.user2_id
		else:
			card.user_id = trade.user1_id
	db.session.commit()	
	
@mod_trade.route('/<id>/myUnusedCards', methods=['POST'])
@login_required
def myUnusedCards(id):
	trade = TradeHeader.query.filter_by(id=id).first()
	if not trade:
		return "No such trade", 400
	if current_user.id != trade.user1_id and current_user.id != trade.user2_id:
                return "You are not involved in this trade", 400
	#fullTrade = returnFullTrade(id)
	usedIds = []
	for line in trade.lines.all():
		usedIds.append(line.card_id)
	trades = TradeHeader.query.filter(or_(TradeHeader.user1_id == current_user.id, TradeHeader.user2_id == current_user.id),TradeHeader.active == True)
	for t in trades:
		for line in t.lines.all():
			usedIds.append(line.card_id)
	user = User.query.filter_by(id=current_user.id).first()
	toReturn = {}
	for userCard in user.cards.filter(~UserCards.id.in_(usedIds)).group_by(UserCards.card_id, UserCards.holo):
		#if userCard.id in usedIds:
		#	continue
		forInsert = {}
		cardRef = Card.query.filter_by(id=userCard.card_id).first()
		forInsert['cardName'] = cardRef.name
		forInsert['cardHolo'] = userCard.holo
		forInsert['quantity'] = user.cards.filter(~UserCards.id.in_(usedIds), UserCards.card_id == userCard.card_id, UserCards.holo == userCard.holo).count()
		toReturn[userCard.id] = forInsert
		#if card.holo:
		#	toReturn[card.id] +=" (holo)"
	return json.dumps(toReturn)
	

@mod_trade.route('/create', methods=['POST'])
@login_required
def create():
	otherUser = User.query.filter_by(id=request.args['otherUserId']).first()
	trade = TradeHeader(user1 = current_user, user2 = otherUser);
	db.session.add(trade)
	db.session.commit()

	tradeLine = TradeLine(trade_id = trade.id, card_id = request.args['cardId'], offering_user = otherUser.id)
	db.session.add(tradeLine)
	db.session.commit()

        return redirect(url_for('trade.showTrade',id = trade.id))
	#return str(otherUserId) + " " + str(current_user.id)

@mod_trade.route('/<id>')
@login_required
def showTrade(id):
	trade = TradeHeader.query.filter_by(id=id).first()
	if not trade:
		return "No such trade", 400
	if current_user.id != trade.user1_id and current_user.id != trade.user2_id:
		return "You are not involved in this trade", 400
	if not trade.active:
                return render_template('trade/complete.html')
	else:
		return render_template('trade/view.html', trade = returnFullTrade(trade.id))

@mod_trade.route('/')
@login_required
def index():
	trades = TradeHeader.query.filter((TradeHeader.user1_id == current_user.id) | (TradeHeader.user2_id == current_user.id),TradeHeader.active == True )
	tradeArray = []
	for trade in trades:
		tradeArray.append(returnFullTrade(trade.id))
	return render_template(	'trade/index.html',
				trades = tradeArray,
				user = current_user)

app/templates/profile/card.html
{% extends "bootstrap/base.html" %}
{% block head %}
{{super()}}
<style>
	{% include "card/cardStyling.html" %}
	{% include "partials/holoEffect.html" %}
	{% include "partials/obscurerEffect.html" %}
</style>
        {% block styles %}
                {{super()}}
                {%include 'main/styling.html'%}
        {% endblock %}
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="/static/js/card/unwrap.js"></script>
{% endblock %}
{% block content %}
	<div class='home_header'>
                <div class='container'>
                        <a href="{{url_for('profiles.cardKind',name=user.name,id=card.id, holo=holo)}}"><h2>{{user.name}}>{{card.name}}</h2></a>
                </div>
        </div>
	{% include "partials/singleCardView.html" %}
	<div class="row">
		<div class="col-md-2 col-md-offset-4">
			{% if ownedCard %}
				<form onsubmit="return confirm('Do you really want to delete this card from your colection?');" action="{{url_for('profiles.deleteCard',name = user.name, cardId = cardLookup.id)}}" method='POST'>
					<input type="submit" class="btn btn-danger" name="delete" value="Delete card"></input>
				</form>
			{% else %}
				<form action="{{url_for('trade.create',otherUserId = user.id, cardId = cardLookup.id)}}" method='POST'>
					<input type="submit" class="btn btn-success" name="trade" value="Start trade"></input>
				</form>
			{% endif %}
		</div>
		<div class="col-md-1">
			<a href="{{url_for('card.showCard', id=card.id)}}" class="btn btn-info">Card master</a>
		</div>
	</div>
	<div class='container'>
		<h1 class="page-header">History</h1>
		{%if cardHistory|length == 0%}
			<h3>This card hasn't been traded</h3>
		{%else%}
			<table class='table table-condensed'>
				<thead>
					<tr><th>Date</th><th>Traded from</th><th>Traded to</th></tr>
				<thead>
				<tbody>
					{%for line in cardHistory%}
					<tr><td>{{line['date']}}</td><td><a href={{url_for('profiles.view',name=line['giving'])}}>{{line['giving']}}</a></td><td><a href={{url_for('profiles.view',name=line['getting'])}}>{{line['getting']}}</a></td></tr>
					{%endfor%}
				</tbody>
			</table>
		{%endif%}
		<h3>This card was pulled on {{origin['date']}} by <a href={{url_for('profiles.view',name=origin['puller'])}}>{{origin['puller']}}</a><h3>
	</div>
{% endblock %}

app/templates/profile/index.html
{% extends "bootstrap/base.html" %}
{% block head %}
	{{super()}}
	{% block styles %}
		{{super()}}
		{%include 'main/styling.html' %}
	{% endblock %}
{% endblock %}
{% block content %}
	<div class='home_header'>
		<div class='container'>
			<h2>Profiles</h2>
		</div>
	</div>
	<div class='container'>
		<table class="table table-hover">
			<caption>Click on a name to visit their profile</caption>
		{% for user in users %}
			<tr>
				<td><a href="{{url_for('profiles.view',name=user.name)}}"><h3>{{user.name}}</h3></a></td>
			</tr>
		{% endfor %}
		</table>
	</div>
{% endblock %}

app/templates/profile/kind.html
{% extends "bootstrap/base.html" %}
{% block head %}
{{super()}}
<style>
	{% include "card/cardStyling.html" %}
	{% include "partials/holoEffect.html" %}
</style>
        {% block styles %}
                {{super()}}
                {%include 'main/styling.html'%}
        {% endblock %}
{% endblock %}
{% block content %}
	<div class='home_header'>
                <div class='container'>
                        <a href="{{url_for('profiles.view',name=user.name)}}"><h2>{{user.name}}</h2></a>
                </div>
        </div>
	{% include "partials/singleCardView.html" %}
	<div class="row">
		<div class="col-md-1 col-md-offset-4">
			<a href="{{url_for('card.showCard', id=card.id)}}" class="btn btn-info">Card master</a>
		</div>
	</div>
	<div class='row'>
	{%for specific in cards %}
		{%if loop.index0%6 == 0 and loop.index0 != 0%}
			</div><div class="row">
		{%endif%}
		<div class='col-md-2'><a href='{{url_for("profiles.viewUserCard",name = user.name,id=specific.id)}}'><h3>{{specific.date_created}}</h3></a></div>
	{%endfor%}
	</div>
	<div class="modal" id="specificModal" tabindex="-1" role="dialog">
        	<div class="modal-dialog modal-sm" role="document">
                	<div class="modal-content">
                        	<div class="modal-header">
                                	<button type="button" class="close" data-dismiss="modal"></button>
                                        <h4 class="modal-title">What do you want to do?</h4>
                                </div>
                                <div class="modal-body">
                                </div>
                                <div class="modal-footer">
                                	<button type="button" class="btn btn-primary" onClick="confirmAdd()">Add these</button>
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                </div>
                	</div>
        	</div>
	</div>
{% endblock %}

app/templates/profile/view.html
{% extends "bootstrap/base.html" %}
{% block head %}
	{{super()}}
	{% block styles %}
		{{super()}}
		{%include 'main/styling.html'%}
		<style>
			.home_header{
				background-color: #c45611;
				color: #efd0bd;
			}
		</style>
	{% endblock %}
{% endblock %}
{% block content %}
	<div class='home_header'>
		<div class='container'>
			<h2>{{user.name}}'s profile</h2>
		</div>
	</div>
	<div class='container'>
		<table class="table table-striped table-hover">
			<tr>
				<th>Card</th>
				<th>Holographic?</th>
			</tr>
			{% for card in cards %}
				<tr>
					<td>
        	                		<h4><a href="{{url_for('profiles.cardKind', name=user.name, id=card.id, holo=holoList[loop.index0])}}">{{card.name}}</a>
						{% if quantities[loop.index0] > 1 %}
							({{quantities[loop.index0]}})
						{% endif %}
						</h4>
					</td>
					<td>
					{%if holoList[loop.index0]%}
						<span class="glyphicon glyphicon-star" style="font-size: 24px" aria-hidden="true"></span>
					{%endif%}
					</td>
				</tr>
        		{% endfor %}
		</table>
	</div>
{% endblock %}