app/mod_card/controllers.py
import random
import os
import json
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for

from sqlalchemy import desc

# Import login manager
from flask.ext.login import LoginManager, UserMixin, login_required, login_user, current_user

# Import the database object from the main app module
from app import db
from app import app

# Import module forms
from app.mod_card.forms import CreateCardForm

# Import module models (i.e. User)
from app.mod_card.models import Card, UserCards
from app.mod_auth.models import User

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_card = Blueprint('card', __name__, url_prefix='/card')

@mod_card.route('/<id>')
@login_required
def showCard(id):
	card = Card.query.filter_by(id=id).first()
	if not card:
		return "That ID doesn't exist", 400
	return render_template( "card/view.html",
				card=card,
				textBackground=app.config['TEXT_BACKGROUND'],
				borderColor=app.config['BORDER_COLOR'])

@mod_card.route('/index')
@mod_card.route('/', methods=['GET','POST'])
def indexCards():
	if request.method == 'GET':
		cards = Card.query.order_by(desc(Card.id)).all()
		return render_template(	"card/index.html",
					cards=cards,
					textBackground=app.config['TEXT_BACKGROUND'],
					borderColor=app.config['BORDER_COLOR'],
					cardsPerRow=app.config['CARDS_PER_ROW'])
	else:
		if request.form['searchTerm'] != '':
			cards = Card.query.filter(Card.name.like("%"+request.form['searchTerm']+"%")).order_by(desc(Card.id)).all()
		else:
			cards = Card.query.order_by(desc(Card.id)).all()
		toReturn = []
		for card in cards:
			toReturn.append([card.name,card.description,url_for('card.showCard', id=card.id), str(card.date_created)])
		return json.dumps(toReturn)

@mod_card.route('/<id>/edit', methods=['GET','POST'])
@login_required
def edit(id):
	card = Card.query.filter_by(id=id).first()
	if card:
		if request.method == 'GET':
			return render_template(	"card/edit.html",
						card=card)
		elif request.method == 'POST':
			card.name = request.form['name']
			card.description = request.form['description']
			card.backgroundColor = request.form['backgroundColor']
			card.holoAllowed = 'holoAllowed' in request.form
			card.holoAlways = 'holoAlways' in request.form
			db.session.commit()
			return redirect(url_for('card.showCard',id = card.id))
			return str(json.dumps(request.form)), 200
		
	else:
		return "That id doesn't exist", 400

@mod_card.route('/<id>/grant', methods=['POST'])
@login_required
def grantCard(id):
	card = Card.query.filter_by(id=id).first()
	if card:
		holo = False
		if (card.holoAllowed and random.randrange(app.config['HOLO_CHANCE']) == 0):
			holo = True
		if (card.holoAlways):
			holo = True			
		user_card = UserCards(card_id = card.id, user_id = current_user.id, holo = holo);
		db.session.add(user_card)
		db.session.commit()
	else:
		return "That id doesn't exist", 400
	origin = {}
        origin['puller'] = current_user.name
        origin['date'] = str(user_card.date_created)[0:10]

	return render_template( "profile/card.html",
                  		user = current_user,
                                card = card,
                                cardLookup = user_card,
                                holo = holo,
                                ownedCard = True,
                                cardHistory = {},
                                origin = origin,
				justPulled = True,
                                textBackground = app.config['TEXT_BACKGROUND'],
                                borderColor = app.config['BORDER_COLOR'])
	return redirect(url_for('profiles.view',name = current_user.name))

@mod_card.route('/<id>/who', methods=['POST'])
@login_required
def who(id):
	card = Card.query.filter_by(id=id).first()
	if card:
		cards = UserCards.query.filter_by(card_id = card.id).group_by(UserCards.user_id)
		toReturn = []
		for i in cards:
			user = User.query.filter_by(id=i.user_id).first()
			count = user.cards.filter(UserCards.card_id == card.id).count()
			r = lambda: random.randint(0,255)
			color = '#{:02x}{:02x}{:02x}'.format(r(),r(),r())
			holo = UserCards.query.filter_by(user_id = i.user_id, card_id = i.card_id, holo = True).first()
			toReturn.append([user.name, (holo != None),count,color])
		return json.dumps(toReturn)
	else:
		return "That id doesn't exist", 400

@mod_card.route('/<id>/delete', methods=['POST'])
@login_required
def delete(id):
	card = Card.query.filter_by(id=id).first()
	if card:
		db.session.delete(card)
        	db.session.commit()
        	return redirect(url_for('card.indexCards'))	
	else:
		return "That isn't a valid id", 400

@mod_card.route('/create/', methods=['GET', 'POST'])
@login_required
def createCard():

	# If sign up form is submitted
	form = CreateCardForm(request.form)

	# Verify the sign up form
	if form.validate_on_submit():
		f = request.files['image']
		filename = ''.join(random.choice('0123456789ABCDEF') for i in range(10))
		f.save(os.path.join(
			app.config['UPLOAD_FOLDER'], filename+'.png'
		))
		card = Card(name=form.name.data,
			description = form.description.data,
			backgroundColor = form.backgroundColor.data,
			holoAlways = form.holoAlways.data,
			holoAllowed = form.holoAllowed.data,
			retired = False,
			imageName = filename
			)
		db.session.add(card)
	#	try:
		db.session.commit()
		card = Card.query.filter_by(imageName = filename).first()
		return redirect(url_for('card.showCard',id = card.id))
	#	except:
	#	flash('Error in creation', 'error')
	return render_template("card/create.html", form=form)

app/templates/card/cardStyling.html
<style>
                        a{
                                text-decoration: none;
                                color: black;
                        }
                        a:hover{
                                text-decoration: none;
                                color:black;
                        }
                        a:visited{
                                text-decoration: none;
                                color:black;
                        }
                        #cardHolder{
                                border-style: double;
                                border-width: 15px;
                                border-color: {{borderColor}};
                                margin-left: 15px;
                        }
                        .row-eq-height {
                                display: -webkit-box;
                                display: -webkit-flex;
                                display: -ms-flexbox;
                                display:         flex;
                        }
</style>

app/templates/card/create.html
{% extends "bootstrap/base.html" %}
{% block content%}
{% macro render_field(field, placeholder=None) %}
{% if field.errors %}
<div>
{% elif field.flags.error %}
<div>
{% else %}
<div>
{% endif %}
    {% set css_class = 'form-control ' + kwargs.pop('class', '') %}
    {{ field(class=css_class, placeholder=placeholder, **kwargs) }}
</div>
{% endmacro %}

<div>
  <div>
    <div class="container">
        <h2>Tips</h2>
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h4 class="panel-title">Warning</h4>
		</div>
		<div class="panel-body">
			<p>You are using an early version of this site. There is basically no validation here, so be careful! Follow all below directions exactly.</p>
		</div>
	</div>
	<div class="panel panel-default">
                <div class="panel-heading">
                        <h4 class="panel-title">Color</h4>
                </div>
                <div class="panel-body">
                        <p>The color field lets you type in the hex value of the color you would like to have displayed as the background of the card. It will fill everywhere except for the image and the area immediatley behind the text.</p>
			<p>A border is added at the end of the card rendering process and its color is currently fixed as gold for every card. This might be maintainable later.</p>
			<p>While you are allowed to specify any color, it is suggested that you base it on how rare you think the card is. Recommended values are as follows:</p>
			<ul>
				<li>Common: <span style="background-color:#111111; color:white">#111111</span></li>
				<li>Uncommon: <span style="background-color:#868d99; color:white">#868d99</span></li>
				<li>Rare: <span style="background-color:#cec814; color:white">#cec814</span></li>
				<li>Mythic: <span style="background-color:#a80a2c; color:white">#a80a2c</span></li>
			</ul>
			<p>Make sure you put in the #</p>
                </div>
        </div>
	<h3 class="page-header">Image</h3>
	<p>This site does not do any image scaling. That means if you upload a picture for your card that is different from the others, it will always look different.</p>
	<p>You are currently allowed to upload anything and the server doesn't check it. Please follow these guidelines:</p>
	<p><strong>PNG files only</strong></p>
	<p><strong>256x256</strong></p>
    </div>
    <div class="container">
    <h1 class="page-header">Create card</h1>
    {% with errors = get_flashed_messages(category_filter=["error"]) %}
    {% if errors %}
    <div>
    {% for error in errors %}
    {{ error }}<br>
    {% endfor %}
    </div>
    {% endif %}
    {% endwith %}

    {% if form.errors %}
    <div>
    {% for field, error in form.errors.items() %}
    {% for e in error %}
    {{ e }}<br>
    {% endfor %}
    {% endfor %}
    </div>
    {% endif %}
    <form method="POST" autocomplete="off" enctype="multipart/form-data" action="." accept-charset="UTF-8" role="form">
      {{ form.csrf_token }}
      {{ render_field(form.name, placeholder="Card name",
                                  autofocus="") }}
      {{ render_field(form.description, placeholder="Description") }}
      {{ render_field(form.backgroundColor, placeholder="#RRGGBB") }}
      <label>Holographics allowed</label>
      {{ render_field(form.holoAllowed) }}
      <label>Holographics always</label>
      {{ render_field(form.holoAlways) }}
      {{ form.image }}
      <div>
      </div>
      <button class="btn btn-success" type="submit" name="submit">Make card!</button>
    </form>
    </div>
  </div>
</div>
{% endblock %}

app/templates/card/edit.html
{% extends "bootstrap/base.html" %}
{% block content%}
	<div class="container">
		<form method="POST" autocomplete="off" enctype="multipart/form-data" accept-charset="UTF-8" role="form">
			<div class="form-group">
				<label for="name">Name</label>
				<input class="form-control" type="text" value="{{card.name}}" name="name" id="name"></input>
			</div>
			<div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control" name="description" id="description">{{card.description}}</textarea>
                        </div>
			<div class="form-group">
                                <label for="backgroundColor">Background color</label>
                                <input class="form-control" type="text" value="{{card.backgroundColor}}" name="backgroundColor" id="backgroundColor"></input>
                        </div>
			<div class="form-group">
                                <label for="holoAllowed">Holographics allowed</label>
                                <input type="checkbox" name="holoAllowed" id="holoAllowed" {% if card.holoAllowed %}checked{%endif%}></input>
                        </div>
			<div class="form-group">
                                <label for="holoAlways">Always holographic</label>
                                <input type="checkbox" name="holoAlways" id="holoAlways" {% if card.holoAlways %}checked{%endif%}></input>
                        </div>
			<button class="btn btn-default" type="submit" name="submit">Save changes</button>
		</form>
	</div>
{% endblock %}

app/templates/card/index.html
{% extends "bootstrap/base.html" %}
{% block head %}
	{{super()}}
	{% include "main/styling.html" %}
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.8/js/jquery.tablesorter.js"></script>
{% block styles %}
	{{super()}}
	<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.8/css/theme.bootstrap_3.min.css" rel="stylesheet">
{% endblock %}
{% block scripts %}
	<script src="/static/js/card/index.js"></script>
{% endblock %}
{% endblock %}
{% block content %}
	<div class='home_header'>
		<div class='container'>
			<h2>Cards</h2>
		</div>
	</div>
	<div class='container'>
		<a class="btn btn-success" href="{{url_for('card.createCard')}}">Make a card</a>
		<input type="text" id="nameSearchInput" placeholder="Search name here"></input>
		<table id = "resultsTable" class='table table-condensed tablesorter'>
			<thead>
				<tr class="tablesorter-headerRow">
					<th>Name</th>
					<th>Description</th>
					<th>Created</th>
				</tr>
			</thead>
			<tbody id="resultsHolder">
			</tbody>
		</table>
	</div>
{% endblock %}

app/templates/card/view.html
{% extends "bootstrap/base.html" %}
{% block head %}
{{super()}}
	<title>{{card.name}}</title>
	{% block metas %}
	{{super()}}
        <meta name="description" content="{{card.description}}">
        <meta name="twitter:card" content="summary">
        <meta name="twitter:title" content = "{{card.name}}">
        <meta name="twitter:description" content="{{card.description}}">
	{% endblock %}
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<style>
	#cardHolder{
		background-color: {{card.backgroundColor}};
		border-style: double;
		border-width: 15px;
		border-color: {{borderColor}};
	}
</style>
	<script>
		function makeChart(passedLabels,passedData,passedColors){
			var ctx = document.getElementById("whoChart").getContext("2d");
			ctx.clearRect(0,0,ctx.width,ctx.height);
			var chart = new Chart(ctx, {
				type: 'doughnut',
				data: {
					labels: passedLabels,
					datasets: [{
						label: "Test",
						data: passedData,
						backgroundColor: passedColors
					}]
				},
				options: {cutoutPercentage: 50}
			});
				
		}
		$(function(){
                        $('#whoModal').on('hidden.bs.modal', function (e) {
                                console.info(e.relatedTarget);
                                $('#whoTable').empty();
                        });
                        $('#whoModal').on('show.bs.modal', function () {
                                $.post("{{url_for('card.who',id=card.id)}}", function( data )
                                {
					console.info(data);
                                        var parsed = JSON.parse(data);
					var labels = new Array();
					var data = new Array();
					var colors = new Array();
					console.info(parsed);
                                        for (var key in parsed)
                                        {
						labels.push(parsed[key][0]);
						data.push(parsed[key][2]);
						colors.push(parsed[key][3]);
						var holoInsert = '<td></td>';
						if (parsed[key][1] == true)
							holoInsert = '<td><span class="glyphicon glyphicon-star"></span></td>';
                                        	$("#whoTable").append('<tr><td>'+parsed[key][0]+'</td>'+holoInsert+'</tr>');
                                        }
					makeChart(labels,data,colors);
                                });
                        });
                });
	</script>
{% endblock %}
{% block content %}
<div class="row">
	<div class = "col-md-3 col-md-offset-4" id=cardHolder style="background-color:{{card.backgroundColor}};">
		<div class="row" style="margin:2%">
                               <h3 style='border-style:solid; margin-top:0px; margin-bottom:0px;background-color:{{textBackground}}'>{{card.name}}</h3>
                       </div>
		<div class="row" style='width:96%; margin-left:2%; margin-right:2%'>
			<img style="width:100%;margin-auto" src='{{url_for('static',filename = 'cardImages/' + card.imageName + '.png')}}'>
		</div>
		<div class="row" style="margin:2%">
			<p style="margin:0;border-style:solid; background-color:{{textBackground}}">{{card.description}}</p>
		</div>
	</div>
</div>
<div class="row">
	<div class = "col-md-2 col-md-offset-4">
		<form method="POST" enctype="multipart/form-data" action="{{url_for('card.grantCard',id=card.id)}}" accept-charset="UTF-8" role="form">
			<button type="submit" class='btn btn-success' name="submit">I earned one</button>
		</form>
	</div>
	<div class = "col-md-1">
		<a style="display:inline-block" href="{{url_for('card.edit', id=card.id)}}" class="btn btn-info">Edit</a>
	</div>
</div>
<div class="row">
	<div class="col-md-2 col-md-offset-4">
		<form  onsubmit="return confirm('Do you really want to delete this card? DO NOT DO THIS IF PEOPLE ALREADY OWN IT');" action="{{url_for('card.delete',id = card.id)}}" method='POST'>
                	<input type="submit" class="btn btn-danger" name="delete" value="Delete card"></input>
                </form>
	</div>
	<div class="col-md-1">
		<button id="whoButton" class='btn btn-default' data-toggle='modal' data-target='#whoModal'>To whom does this card belong?</button>
	</div>
</div>
<div class="modal" id="whoModal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
        	<div class="modal-content">
                	<div class="modal-header">
                        	<button type="button" class="close" data-dismiss="modal"></button>
                        	<h4 class="modal-title">Here's who has that</h4>
                        </div>
                        <div class="modal-body">
				<canvas id="whoChart"></canvas>
                        	<div id="whoShower">
                                	<table class="table table-condensed bg-info" id="whoTable">
                                        </table>
                                </div>
                        </div>
                        <div class="modal-footer">
                        	<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        </div>
                </div>
        </div>
</div>
{% endblock %}